POST http://localhost:3001/api/knjige
content-Type: application/json

{
    "posudeno": " ",
    "grada": "Gradska knjiznica Marka Marulica",
    "naslov": "The peoplewatching",
    "autor": "Desmond Morris",
    "korisnik":"6223882cbe4909e3ad9f8d49"
    
}