POST http://localhost:3001/api/knjige
content-Type: application/json

{
    "posudeno": " ",
    "grada": "Gradska knjiznica Marka Marulica",
    "naslov": "Žene koje trće s vukovima",
    "autor": "Clarissa Pinkola Estes"
    
}